apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-sa
  namespace: k8s-security-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: agent-role
  namespace: k8s-security-system
rules:
  - apiGroups: [""]
    resources: ["pods", "events"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agent-rolebinding
  namespace: k8s-security-system
subjects:
  - kind: ServiceAccount
    name: agent-sa
    namespace: k8s-security-system
roleRef:
  kind: Role
  name: agent-role
  apiGroup: rbac.authorization.k8s.io
