apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: security-agent
  namespace: k8s-security-system
spec:
  selector:
    matchLabels:
      app: security-agent
  template:
    metadata:
      labels:
        app: security-agent
    spec:
      serviceAccountName: agent-sa
      containers:
        - name: agent
          image: myorg/security-agent:latest
          args:
            - "--forward-endpoint=http://controller.k8s-security-system.svc:8080"
          volumeMounts:
            - name: varlog
              mountPath: /var/log
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
            type: Directory
